use anyhow::Result;
use crate::persistence::sqlite::{Database, TimelineRow};

/// Registers a timeline event in the database.
pub fn register_event(
    db: &Database,
    event: &str,
    impact: &str,
    timestamp: &str,
) -> Result<()> {
    let id = uuid::Uuid::new_v4().to_string();
    db.insert_timeline_event(&id, event, impact, timestamp)?;
    Ok(())
}

/// Retrieves all timeline events from the database.
pub fn get_all_events(db: &Database) -> Result<Vec<TimelineRow>> {
    db.get_all_timeline_events()
}

/// Generates a markdown timeline string from stored events.
pub fn generate_timeline_markdown(events: &[TimelineRow]) -> String {
    let mut md = String::new();
    md.push_str("# Project Timeline\n\n");
    md.push_str("> Generated by ChronoDrake Core v0.3\n\n");
    md.push_str("| Date | Event | Impact |\n");
    md.push_str("|------|-------|--------|\n");

    for event in events.iter().rev() {
        md.push_str(&format!(
            "| {} | {} | {} |\n",
            event.timestamp, event.event, event.impact
        ));
    }

    md.push_str("\n---\n");
    md.push_str("*This file was automatically generated by ChronoDrake Core v0.3*\n");
    md
}
