use anyhow::Result;
use std::path::Path;

use crate::models::ProjectScan;

/// Generates an AI_HANDOFF.md file from a scan result.
///
/// This file provides a universal handoff document that any AI (ChatGPT, Claude,
/// Gemini, DeepSeek, etc.) can read to understand the project context immediately.
pub fn generate_ai_handoff(scan: &ProjectScan, output_dir: &str) -> Result<String> {
    let output_path = Path::new(output_dir).join("AI_HANDOFF.md");
    let mut content = String::new();

    // Header
    content.push_str("# 🤖 AI Handoff — ChronoDrake\n\n");
    content.push_str("> **Universal AI Continuity Document**\n");
    content.push_str("> This file enables seamless handoff between AI assistants.\n\n");

    content.push_str("---\n\n");

    // Section 1: Project Identity
    content.push_str("## 1. Project Identity\n\n");
    content.push_str(&format!("- **Root Path:** `{}`\n", scan.root_path));
    content.push_str(&format!("- **Scan Timestamp:** `{}`\n", scan.scanned_at));
    content.push_str(&format!("- **Scanner:** ChronoDrake Core v0.1\n"));

    // Section 2: Detected Stack
    content.push_str("\n## 2. Detected Technology Stack\n\n");
    content.push_str("| Technology | Category | Status |\n");
    content.push_str("|------------|----------|--------|\n");

    for tech in &scan.technologies {
        let status = if tech.detected { "✅ Present" } else { "❌ Absent" };
        content.push_str(&format!("| {} | {} | {} |\n", tech.name, tech.category, status));
    }

    // Section 3: Project Structure
    content.push_str("\n## 3. Project Structure\n\n");
    if let Some(config_files) = scan.findings.get("config_files") {
        content.push_str("### Configuration Files\n\n");
        for file in config_files {
            content.push_str(&format!("- `{}`\n", file));
        }
        content.push_str("\n");
    }
    if let Some(lock_files) = scan.findings.get("lock_files") {
        content.push_str("### Lock Files\n\n");
        for file in lock_files {
            content.push_str(&format!("- `{}`\n", file));
        }
        content.push_str("\n");
    }

    // Section 4: AI Context
    content.push_str("\n## 4. AI Context\n\n");
    content.push_str("This project was scanned by **ChronoDrake Core v0.1**.\n\n");
    content.push_str("### Capabilities\n\n");
    content.push_str("- ✅ Project technology detection\n");
    content.push_str("- ✅ Filesystem scanning\n");
    content.push_str("- ✅ Memory persistence (PROJECT_STATUS.md)\n");
    content.push_str("- ✅ AI handoff generation\n\n");

    content.push_str("### Limitations (v0.1)\n\n");
    content.push_str("- ❌ No AI integration yet\n");
    content.push_str("- ❌ No embeddings / vector DB\n");
    content.push_str("- ❌ No cloud sync\n");
    content.push_str("- ❌ No UI\n\n");

    // Section 5: Instructions for AI
    content.push_str("## 5. Instructions for AI Assistants\n\n");
    content.push_str("When you receive this handoff document, please:\n\n");
    content.push_str("1. Read this entire document to understand the project context.\n");
    content.push_str("2. Check `PROJECT_STATUS.md` for detailed scan results.\n");
    content.push_str("3. Use the detected technology stack to inform your responses.\n");
    content.push_str("4. Maintain continuity by referencing the scan timestamp.\n");
    content.push_str("5. Update this document if the project structure changes.\n\n");

    // Footer
    content.push_str("---\n\n");
    content.push_str("*This handoff document was automatically generated by ChronoDrake Core v0.1*\n");
    content.push_str("*ChronoDrake — AI Continuity Operating System*\n");

    std::fs::write(&output_path, &content)?;

    Ok(output_path.to_string_lossy().to_string())
}
